-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 'v0.5.1'
    hooks:
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: check-json
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: flake8
    -   id: name-tests-test
        exclude: tests/(integration/testcases\.py|helpers\.py)
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
